# Generated by Django 6.0.3 on 2026-03-21 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_alter_todoitem_options_todoitem_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
